# Generated by Django 2.2.7 on 2019-11-16 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='due_date',
            field=models.DateField(default=datetime.date(2019, 11, 16)),
        ),
    ]
