# Generated by Django 2.2.7 on 2019-11-16 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_list_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
