# Generated by Django 2.2.7 on 2019-11-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_auto_20191116_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='due_date',
        ),
    ]
