# Generated by Django 2.2.7 on 2019-11-17 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0011_auto_20191117_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 18, 18, 24, 47, 588051), null=True),
        ),
    ]
