# Generated by Django 2.2.7 on 2019-11-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0012_auto_20191117_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
