# Generated by Django 2.2.7 on 2019-11-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0013_auto_20191117_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='item',
            new_name='name',
        ),
    ]
