# Generated by Django 2.2.7 on 2019-11-17 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0014_auto_20191117_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 18, 19, 57, 40, 875089), null=True),
        ),
    ]
