# Generated by Django 2.2.7 on 2019-11-17 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0016_auto_20191117_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 18, 20, 27, 38, 704406), null=True),
        ),
    ]
